services:
  - type: web
    name: appweb
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python app.py
    autoDeploy: false
